---
abstract: 'Perl extension for the Google Safe Browsing v2 API. (Google Safe Browsing v1 has been deprecated by Google.)'
author:
  - 'Julien Sobrier <julien@sobrier.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-SafeBrowsing2
no_index:
  directory:
    - t
    - inc
requires:
  Digest::HMAC_SHA1: 0
  Digest::SHA: 0
  File::Slurp: 0
  LWP::UserAgent: 0
  List::Util: 0
  MIME::Base64: 0
  MIME::Base64::URLSafe: 0
  Net::IPAddress: 0
  String::HexConvert: 0
  Test::More: 0
  Text::Trim: 0
  URI: 0
  constant: 0
version: 1.08
