--- #YAML:1.0
name:               Net-Google-SafeBrowsing2
version:            0.1
abstract:           Perl extension Google Safe Browsing v2
author:
    - Julien Sobrier <julien@sobrier.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    constant:        0
    Digest::SHA:     0
    List::Util:      0
    LWP::UserAgent:  0
    Net::IPAddress:  0
    Switch:          0
    Test::More:      0
    Text::Trim:      0
    URI:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
