# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Google-SafeBrowsing2
version:      1.06
version_from: lib/Net/Google/SafeBrowsing2.pm
installdirs:  site
requires:
    constant:                      0
    Digest::HMAC_SHA1:             0
    Digest::SHA:                   0
    List::Util:                    0
    LWP::UserAgent:                0
    MIME::Base64:                  0
    MIME::Base64::URLSafe:         0
    Net::IPAddress:                0
    String::HexConvert:            0
    Test::More:                    0
    Text::Trim:                    0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
