--- #YAML:1.0
name:               Net-Google-SafeBrowsing2
version:            1.0
abstract:           Perl extension for the Google Safe Browsing v2 API.
author:
    - Julien Sobrier <julien@sobrier.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    constant:             0
    Digest::HMAC_SHA1:    0
    Digest::SHA:          0
    List::Util:           0
    LWP::UserAgent:       0
    MIME::Base64:         0
    MIME::Base64::URLSafe:  0
    Net::IPAddress:       0
    Test::More:           0
    Text::Trim:           0
    URI:                  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
